---
title: "Notes"
description-meta: "Teaching notes and reading notes by Juncheng Zhang"
page-navigation: false
title-block-banner: false
---

Notes on solving the current-value Hamiltonian using the Lagrangian approach.

- [Macro Current-value Hamiltonian (PDF)](files/notes/JZ_Macro_Current-value Hamiltonian.pdf){target="_blank"}

Notes for Python Programming for Economics (Autumn 2025)

Materials for ECON1059 seminars. PDF files are for quick reading, and notebooks are for running or editing the code.

| Seminar | PDF | Notebook |
|---|---|---|
| Seminar 1 | [PDF](files/notes/econ1059-autumn-2025/Seminar_1.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_1.ipynb){target="_blank"} |
| Seminar 2 | [PDF](files/notes/econ1059-autumn-2025/Seminar_2.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_2.ipynb){target="_blank"} |
| Seminar 3 | [PDF](files/notes/econ1059-autumn-2025/Seminar_3.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_3.ipynb){target="_blank"} |
| Seminar 4 | [PDF](files/notes/econ1059-autumn-2025/Seminar_4.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_4.ipynb){target="_blank"} |
| Seminar 5 | [PDF](files/notes/econ1059-autumn-2025/Seminar_5.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_5.ipynb){target="_blank"} |
| Seminar 6 | [PDF](files/notes/econ1059-autumn-2025/Seminar_6.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_6.ipynb){target="_blank"} |
| Seminar 7 | [PDF](files/notes/econ1059-autumn-2025/Seminar_7.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_7.ipynb){target="_blank"} |
| Seminar 8 | [PDF](files/notes/econ1059-autumn-2025/Seminar_8.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_8.ipynb){target="_blank"} |
| Seminar 9 | [PDF](files/notes/econ1059-autumn-2025/Seminar_9.pdf){target="_blank"} | [ipynb](files/notes/econ1059-autumn-2025/Seminar_9.ipynb){target="_blank"} |


