---
title: "Research"
description-meta: "Research interests of Juncheng Zhang"
title-block-banner: false
---

My research focuses on experimental and behavioural economics and decision theory, with a particular interest in how self-perception influences economic decision-making in labour market and search environments. My research primarily employs experimental methods to test theoretical predictions and study individual behaviour, while I also conduct empirical research on related topics.


## Working Papers

[1] **“Sequential job search with ego utility.”** With [Marcus Roel](https://www.marcusroel.com/), [Stuart McDonald](https://research.nottingham.edu.cn/en/persons/stuart-mcdonald/), and [Shuo Yang](https://research.nottingham.edu.cn/en/persons/will-yang/). *Preparing for submission.*

[2] **“Too scared to search? A model of ego utility in job search.”** With [Marcus Roel](https://www.marcusroel.com/), [Stuart McDonald](https://research.nottingham.edu.cn/en/persons/stuart-mcdonald/), and [Shuo Yang](https://research.nottingham.edu.cn/en/persons/will-yang/). *Presented at the 3rd Xiangjiang River Forum in Economics, Finance and Management for Young Scholars, Hunan University, 2024.*

[3] **“Early-career adaptation under China’s dual-track academic system: Evidence from overseas-trained economists.”** With [Lin Lin](https://faculty.ecnu.edu.cn/_s35/ll2_en_17023/main.psp), [Stuart McDonald](https://research.nottingham.edu.cn/en/persons/stuart-mcdonald/), Zengbao Hu, and [Bo Wang](https://bowang16.weebly.com/). *Submitted.*

## Work in Progress

[1] **“Ego utility and information preferences: Experimental evidence.”** With [Shuo Yang](https://research.nottingham.edu.cn/en/persons/will-yang/), [Stuart McDonald](https://research.nottingham.edu.cn/en/persons/stuart-mcdonald/), and [Marcus Roel](https://www.marcusroel.com/). *Manuscript in preparation.*

[2] **“Weight-Related Feedback, Self-Image Concerns, and Engagement in Weight Management.”** *Early-stage project.*
